### ISSUE TITLE
Add Initial Support for Skype

### ISSUE THREAD

**Issue by darkmorpher** [ifwe/digsby#17]
Since Microsoft planned to shutdown the WLM software and stop the Messenger service by next year, it would be wise to finally add initial support for Skype in Digsby.

https://dev.skype.com/skypekit

**Comment by vicary** [comment]
+1 The community (if it's still there) would love this.

**Comment by Stelminator** [comment]
https://github.com/tagged/digsby/tree/master/digsby/devplugins/skype

**Comment by darkmorpher** [comment]
Just so everyone know, Skype will retire their desktop API later this year. Support for some part of the features are extended until further notice, but third-party applications will cease working.
Read the official post [here](http://blogs.skype.com/2013/11/06/feature-evolution-and-support-for-the-skype-desktop-api/).

You probably have to end up doing something like [this](http://wiki.miranda-ng.org/index.php?title=Plugin:SkypeClassic/en).

**Comment by darkmorpher** [comment]
[Trillian already ditched Skype](http://blog.trillian.im/?p=2999), since Microsoft acquisition, who decided to [retire their desktop API](http://blogs.skype.com/2013/11/06/feature-evolution-and-support-for-the-skype-desktop-api) and SkypeKit.

[@skypeopensource](http://skype-open-source.blogspot.com) seems to be reverse engineering Skype and releasing it's library files.
