### ISSUE TITLE
Gmail notifications are not appearing for multiple users.

### ISSUE THREAD

**Issue by hobs** [ifwe/digsby#19]
I have been having issues the last week with the gmail notifications being completely missing in digsby, but I thought it was a personal problem, however, checking the forums it does appear that several people are running into this issue.

The issue manifests as having no notifications, I looked at some of the code and it mentioned crawling the atom feed, so I checked that, and the atom feed definitely showed the new emails I had awaiting, but I didnt see the same url as I used in the associated code (https://mail.google.com/mail/feed/atom). 

I also checked the digsby logs, and if you would like I could upload them somewhere, but they seem to indicate that digsby checks and finds no new mail, and that all things are ok.

2013-04-25 00:32:20.634,20,INFO,gmail,"<Gmail u'email@gmail.com (gmail) Checking Mail..., '', enabled> got 0 new messages Thu Apr 25 00:32:20 2013",plugins\component_gmail\gmail.pyo,gmail.pyo,gmail,finish_update,362,1366867940.634000,21222,AsyncoreThread,4028,5020

If I could help repro or provide any information or help, I would be glad to pitch in, just let me know what you would like to know!

**Comment by ulfgj** [comment]
just confirming. having the same issue.

**Comment by jrinco11** [comment]
It may have to do with the "always use https" setting within gmail?  I was trying to figure out why the official "Gmail Notifier" (tray icon notifier) wasn't working, and it was due to the above setting and one has to download a registry patch to set the gmail url to https (vs http).   In digsby, if I setup IMAP checking (instead of the built in gmail checker), using 993 as the IMAP port, it works fine.  (though, the built in gmail checker after disabling always use https doesn't make it start working again)

**Comment by zyber** [comment]
I use Digsby for 5 different Gmail, a Ymail and a Twitter account. As of last week all the Gmail accounts will not show any notifications even though they are connected.  The Twitter and Ymail accounts are working as normal.
Any help (in simple terms) would be appreciated.

**Comment by hobs** [comment]
@zyber Nothing in the digsby code changed, so it is likely either something in the pipeline of how they are getting the information changed or something expired, etc.
That's the problem with working with third party services, what works today may not work tomorrow.

**Comment by Stelminator** [comment]
We're using the notifier's API, and always do https.

https://github.com/tagged/digsby/blob/master/digsby/src/plugins/component_gmail/gmail.py#L68 (among other lines).

**Comment by kojot1234** [comment]
Will there be fix for this? I'd love to have the notifications working again. Anything I can do on my part?

Edit: For the time being if you want to have the notifications showing up you can add a google imap email. Settings below:

<b>Email Address:</b> youremail@google.com
<b>Username:</b> youremail@google.com
<b>Password:</b> your_pwd
<b>IMAP server:</b> imap.gmail.com (Check SSL box, port 993)
<b>SMTP server:</b> smtp.gmail.com (Check SSL box, port 465)

**Comment by ulfgj** [comment]
just pray...

On Tue, Apr 30, 2013 at 4:45 PM, kojot1234 notifications@github.com wrote:

> Will there be fix for this? I'd love to have the notifications working
> again. Anything I can do on my part?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/tagged/digsby/issues/19#issuecomment-17231492
> .

## 

:: ulf gjerdingen
http://www.myspace.com/ulfgj
http://ulf.wz.cz

**Comment by darkmorpher** [comment]
I'm having the same issue for more than 2 weeks now. Guess I'm stuck with Pidgin for now :\

**Comment by vicary** [comment]
@ulfgj :+1: consider it at least a positive contribution to this project.

**Comment by iliepandia** [comment]
Hello,

If you don't want to wait for the official build you can patch your install with the instructions here:

http://softconsultant.ro/2013/05/13/solution-for-digsby-gmail-notifications/

**Comment by bloodydom666** [comment]
I downland patch from link and look at in file compare
what dose 'my_log' do ?
is this debug code ?

**Comment by iliepandia** [comment]
Yes, it was a function that I've been using during debug time trying to determine why it was no longer showing up anything!

**Comment by iliepandia** [comment]
Use this to decompile that .pyo file if you're worried: 
http://sourceforge.net/projects/decompyle/

Or you can simply replace that .pyo file with the gmail.py source code from GIT that I've submitted and it will still work.

**Comment by mikedougherty** [comment]
Closing this as the fix is in #20. Will be shipped as soon as I can get a working build going :/

**Comment by acturbo** [comment]
yahoo @ymail.com (not @gmail.com) is not working on both of my accounts. Started happening recently as in the past few weeks (at least)
