### ISSUE TITLE
Google Hangout and future of gTalk video chat

### ISSUE THREAD

**Issue by darkmorpher** [ifwe/digsby#28]
So now that _Google_ has shutdown the gTalk messenger and requiring everyone to download _Chrome_ for to use **Google+ Hangouts** (gTalk replacement), will Digsby remove support for Google chat+video service? Or is there a way to add support for this so called "Hangouts"?
I'm asking this cause Digsby doesn't support video chat now.

**Comment by nairbd** [comment]
There doesn't seem to be any active development on Digsby since it went open source

**Comment by darkmorpher** [comment]
Seems like it. Main Digsby.com page has redirection issues. Their twitter hasn't been updated since Sep. And the GitWiki is empty since this repo has been created.

**Comment by Brok3nHalo** [comment]
The existing gTalk text chat should continue to work for the foreseeable future. At least, last I read, Google claims it should remain be a functional interface to Hangouts.

As for adding Hangout support for video, or chat in the case of them dropping XMPP chat support for that matter, it should be possible but Google hasn't publicized the API for either so the protocol would have to be reverse engineered in order to be implemented.

@darkmorpher Where are the redirection issues? After seeing this I took a look at the site but didn't have an issue.

**Comment by darkmorpher** [comment]
@Brok3nHalo I saw what seems like partial API [here](https://developers.google.com/+/hangouts/api)

And about the redirection, I'm seeing [this](removed.link)

**Comment by Brok3nHalo** [comment]
@darkmorpher Yeah, I looked through that API the other day. Unfortunately it doesn't cover the chat protocol at all and the audio/video stuff is very limited. It's just meant to access settings like volume and stuff in plugins for the website.

The digsby.com issue is an odd one. Going to the site works fine for me in FireFox on Windows. Only things I could think is a bug in the build of FireFox you're using or some sort of issue with a certain ISP?

**Comment by darkmorpher** [comment]
@Brok3nHalo

**Update 2015:** [This redirecting issue](http://www.digsby.com) still exists! Regardless of browser version.
I can load other pages/sub-domains though, (like [this page](http://www.digsby.com/download.php) - _weird_.)

**Comment by darkmorpher** [comment]
Google did mention something about a full [API](https://developers.google.com/+/hangouts/api/index-all) release sometime in 2014, but the API support for a desktop client is a pipe dream.
They are pushing for more people to use _Chrome_ based browsers, in order to use their services.

[**Trillian**](trillian.im) is just waiting to ditch Google Talk/Hangouts' support (partial), because of this.
[They already ditched Skype](http://blog.trillian.im/?p=2999), who, since Microsoft acquisition, have decided to [**retire their desktop API**](http://blogs.skype.com/2013/11/06/feature-evolution-and-support-for-the-skype-desktop-api).
**Imo.im** already dropped the support for all third-party IM networks and become a standalone platform of their own.

I guess the age of _Interoperability_ clients, is coming to an _end..._
