### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by selmisha** [ifwe/digsby#35]
Anyone having issue sending or receiving IM's today? I can see users active on my contact list, however when I send a message they do not receive it nor do I get their messages. I've tested this with Gchat, AOL, Facebook and Yahoo, all with the same results.

**Comment by Brok3nHalo** [comment]
That's a strange issue. Have you tried rebooting? Each network goes over it's own connection so they all stopped working at once it's probably related to your computer or network. Is this at home or an office? If it's an office network maybe they blocked chat?

**Comment by selmisha** [comment]
I duplicated it on two machines in two different locations (home vs work) and got the same result. I'm headed into the office in a bit and will test it again. The whole thing was really odd.

**Comment by selmisha** [comment]
Today it's fine. A little slow, but otherwise it's working fine.
